# https://taskfile.dev

version: '3'

tasks:
  run: 
    desc: Run the application
    cmds: 
    - GOFLAGS=-mod=mod go run acid_interblend/main.go
  run-mobile:
    desc: run on mobile emulator
    cmds: 
    - GOFLAGS=-mod=mod go run -tags mobile acid_interblend_gui/main.go
  build: 
    desc: Build the application
    cmds: 
    - GOFLAGS=-mod=mod go build -o build/acis_blend main.go
  build_gui: 
    desc: Build the application
    cmds: 
    - GOFLAGS=-mod=mod go build -o build/acis_blend_gui acid_interblend_gui/main.go 
  package-android: 
    desc: build the package for android
    cmds:
    - fyne package -os android -appID de.afeldman.acid -icon acid.png --src acid_interblend_gui --name acid_blend_gui --release
  package-ios: 
    desc: build the package for ios
    cmds:
    - fyne package -os ios -appID de.afeldman.acid -icon acid.png --src acid_interblend_gui --name acid_blend_gui --release
  package-windows: 
    desc: build the package for windows
    cmds:
    - fyne package -os windows -appID de.afeldman.acid -icon acid.png --src acid_interblend_gui --name acid_blend_gui --release
  package-linux: 
    desc: build package for linux
    cmds:
    - fyne package -os linux -appID de.afeldman.acid -icon acid.png --src acid_interblend_gui --name acid_blend_gui --release
  clean: 
    desc: clean the application
    cmds: 
    - rm -rf dist
  default:
    cmds:
    - GOFLAGS=-mod=mod go run acid_interblend_gui/main.go
